"""empty message

Revision ID: e3452c067837
Revises: f3ee0e5d0ee4
Create Date: 2022-07-26 08:58:21.125347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3452c067837'
down_revision = 'f3ee0e5d0ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_likes', 'id')
    op.drop_column('image_likes', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_likes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('comment_likes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
