"""empty message

Revision ID: f3ee0e5d0ee4
Revises: de180d6a045f
Create Date: 2022-07-25 14:17:01.378664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ee0e5d0ee4'
down_revision = 'de180d6a045f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=40), nullable=False))
    op.add_column('images', sa.Column('username', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'username')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
